import React from "react";
import { Layout, Button, Descriptions, PageHeader } from 'antd';

const { Content, Header } = Layout;
export default function MainContent(props) {
  return (
    <div>
        <PageHeader
          className="site-page-header-responsive"
          ghost={false}
          title="Dashboards"
          extra={[
            <Button key="1" type="default" style={{
               fontFamily: "Arial, Tahoma, Verdana, sans-serif;",
               fontSize: "1em",
               background: "#0275b8", 
               borderColor: "1px solid #0275b8",  
               borderRadius: "2px",
               color: '#fff'
               }}>
              Create Dashboard
            </Button>
          ]}
          style={{
            alignItems: 'center',
            height: '45px',
            padding: '0 10px',
            background: '#ffffff',
            borderBottom: '1px solid #dfe4e',
            lineHeight: 0
          }}
        >
        </PageHeader>


      <Content style={{ margin: "24px 16px 0", overflow: "initial" }}>
        <div style={{ padding: 24, background: "#fff", textAlign: "center" }}>
          ...
          <br />
          test
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          test
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          content
        </div>
      </Content>
    </div>

  );
}
